### ISSUE TITLE
[discussion] Can you explain why NetErnals isn't recommended ?

### ISSUE THREAD

**Issue by foxjaw** [Sr-Han/kernel_xiaomi_mojito#2]
Can you explain why @cyberknight777 doesn't recommend NetErnels fork of kernelsu ?

**Comment by cyberknight777** [comment]
Because KernelSU is unsafe and intrusive. I will never ship it and I don’t endorse shipping it with my kernel.

**Comment by foxjaw** [comment]
Oh. Tq for replying sir. Can you provide an existing blog post that discusses about this intrusiveness ? I wanna know how harmful this is...  
Caz I'm trying new ways to root android & found kernelsu worth, caz banking apps doesn't even know whether the device is rooted or not.

**Comment by cyberknight777** [comment]
There is no blogpost about it yet however from looking at the source code, KernelSU gets root via some suspicious ways and not to mention via KernelSU, one can get hacked as it is built into the kernel as compared to magisk that patches the boot.img. I’m not advocating for magisk here however as both are equally insecure but if you really care about banking apps, you shouldn’t be rooted IMO. Being rooted breaks a chain of trust that should never be broken anyhow. That said I’d never use KernelSU at all. If I really need root, I can build a userdebug ROM for adb root or patch boot and flash but never to use KSU. You are free to use it but don’t ever come to me if you have bugs, it is to why I don’t endorse it because it’s not my kernel. I’ll never officially ship ksu. This is simply a custom fork with KSU so it’s not my problem if you have bugs or whatever else with it.

**Comment by foxjaw** [comment]
Understood. So it's just your idealogical perspective towards kernelsu being kernel patched instead of boot patched dynamically.  
Tbh, this kernelsu fork is actually unofficial & not recommended by kernelsu team either. Hence, I would be skeptical too.  

I'm hoping for the future where there would a possibility to patch any kernel dynamically through recovery or existing root (magisk/su) by official kernelsu team. This way, there won't be any middlemen between kernelsu & end device.

**Comment by cyberknight777** [comment]
> @cyberknight777 Tbf, android is developed by google. They literally took mainstream linux, and distributed the kernel/system layer in a way so that su doesn't exist. If you use a Linux machine, and if you are the owner of your personal computer, why would you avoid super user previleges ? It just didn't make sense.
> 
> It's very hard to use Android without previleges. Now it's becoming harder than ever with certain apps needing safetynet. KernelSU is a step in a right direction tbh. It avoids all of these safetynet issues to the kernel level.
> 
> If you ask me, users should not use magisk at all. Kernelsu is way more user friendly and safetynet proof.

You don’t really have to explain how an android kernel works to me. Don’t compare a Linux distribution and Android. You don’t have sudo, nor do you have a locked root account in Android so comparing is worthless. It’s not “hard” to use Android without root as that’s pretty much subjective. You shouldn’t even bring the safetynet factor as safetynet is deprecated which brings us to the intermediate future: Play Integrity. Even if you use KernelSU or not, you will keep failing. Google is killing off all older devices’ so spoofin em is not gonna work in sometime anyways. KernelSU is not a “step in the right direction”, as a kernel developer I know for a fact that KernelSU is unsafe, intrusive, overheady so I’ll never recommend using it. Magisk is similar yet you only have one source to patch boot and flash it from. Unlike having some random person to incorporate into the kernel which then he could also incorporate a malware if he wants to aswell. If you wanna preach for KernelSU, don’t ping me. As a kernel developer I’ve made up my mind, nothing is going to change that.
